In [1]:
!wget https://raw.githubusercontent.com/alexjolly28/entri_DSML/main/resources/emails.csv

--2024-04-24 07:37:46--  https://raw.githubusercontent.com/alexjolly28/entri_DSML/main/resources/emails.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.111.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 31243156 (30M) [text/plain]
Saving to: ‘emails.csv’

emails.csv          100%[===================>]  29.79M  --.-KB/s    in 0.1s    

2024-04-24 07:37:47 (201 MB/s) - ‘emails.csv’ saved [31243156/31243156]



In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [3]:
data = pd.read_csv('emails.csv')
data

Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey  \
0        Email 1    0   0    1    0    0   0    2    0    0  ...         0   
1        Email 2    8  13   24    6    6   2  102    1   27  ...         0   
2        Email 3    0   0    1    0    0   0    8    0    0  ...         0   
3        Email 4    0   5   22    0    5   1   51    2   10  ...         0   
4        Email 5    7   6   17    1    5   2   57    0    9  ...         0   
...          ...  ...  ..  ...  ...  ...  ..  ...  ...  ...  ...       ...   
5167  Email 5168    2   2    2    3    0   0   32    0    0  ...         0   
5168  Email 5169   35  27   11    2    6   5  151    4    3  ...         0   
5169  Email 5170    0   0    1    1    0   0   11    0    0  ...         0   
5170  Email 5171    2   7    1    0    2   1   28    2    0  ...         0   
5171  Email 5172   22  24    5    1    6   5  148    8    2  ...         0   

      jay  valued  lay  infrastructure  military  allowing  ff  dry  \
0       0       0    0               0         0         0   0    0   
1       0       0    0               0         0         0   1    0   
2       0       0    0               0         0         0   0    0   
3       0       0    0               0         0         0   0    0   
4       0       0    0               0         0         0   1    0   
...   ...     ...  ...             ...       ...       ...  ..  ...   
5167    0       0    0               0         0         0   0    0   
5168    0       0    0               0         0         0   1    0   
5169    0       0    0               0         0         0   0    0   
5170    0       0    0               0         0         0   1    0   
5171    0       0    0               0         0         0   0    0   

      Prediction  
0              0  
1              0  
2              0  
3              0  
4              0  
...          ...  
5167           0  
5168           0  
5169           1  
5170           1  
5171           0  

[5172 rows x 3002 columns]

In [4]:
data.head()

Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey  jay  \
0   Email 1    0   0    1    0    0   0    2    0    0  ...         0    0   
1   Email 2    8  13   24    6    6   2  102    1   27  ...         0    0   
2   Email 3    0   0    1    0    0   0    8    0    0  ...         0    0   
3   Email 4    0   5   22    0    5   1   51    2   10  ...         0    0   
4   Email 5    7   6   17    1    5   2   57    0    9  ...         0    0   

   valued  lay  infrastructure  military  allowing  ff  dry  Prediction  
0       0    0               0         0         0   0    0           0  
1       0    0               0         0         0   1    0           0  
2       0    0               0         0         0   0    0           0  
3       0    0               0         0         0   0    0           0  
4       0    0               0         0         0   1    0           0  

[5 rows x 3002 columns]

In [5]:
data.describe()

the           to          ect          and          for  \
count  5172.000000  5172.000000  5172.000000  5172.000000  5172.000000   
mean      6.640565     6.188128     5.143852     3.075599     3.124710   
std      11.745009     9.534576    14.101142     6.045970     4.680522   
min       0.000000     0.000000     1.000000     0.000000     0.000000   
25%       0.000000     1.000000     1.000000     0.000000     1.000000   
50%       3.000000     3.000000     1.000000     1.000000     2.000000   
75%       8.000000     7.000000     4.000000     3.000000     4.000000   
max     210.000000   132.000000   344.000000    89.000000    47.000000   

                of            a          you          hou           in  ...  \
count  5172.000000  5172.000000  5172.000000  5172.000000  5172.000000  ...   
mean      2.627030    55.517401     2.466551     2.024362    10.600155  ...   
std       6.229845    87.574172     4.314444     6.967878    19.281892  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000    12.000000     0.000000     0.000000     1.000000  ...   
50%       1.000000    28.000000     1.000000     0.000000     5.000000  ...   
75%       2.000000    62.250000     3.000000     1.000000    12.000000  ...   
max      77.000000  1898.000000    70.000000   167.000000   223.000000  ...   

          connevey          jay       valued          lay  infrastructure  \
count  5172.000000  5172.000000  5172.000000  5172.000000     5172.000000   
mean      0.005027     0.012568     0.010634     0.098028        0.004254   
std       0.105788     0.199682     0.116693     0.569532        0.096252   
min       0.000000     0.000000     0.000000     0.000000        0.000000   
25%       0.000000     0.000000     0.000000     0.000000        0.000000   
50%       0.000000     0.000000     0.000000     0.000000        0.000000   
75%       0.000000     0.000000     0.000000     0.000000        0.000000   
max       4.000000     7.000000     2.000000    12.000000        3.000000   

          military     allowing           ff          dry   Prediction  
count  5172.000000  5172.000000  5172.000000  5172.000000  5172.000000  
mean      0.006574     0.004060     0.914733     0.006961     0.290023  
std       0.138908     0.072145     2.780203     0.098086     0.453817  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.000000     0.000000     0.000000     0.000000  
50%       0.000000     0.000000     0.000000     0.000000     0.000000  
75%       0.000000     0.000000     1.000000     0.000000     1.000000  
max       4.000000     3.000000   114.000000     4.000000     1.000000  

[8 rows x 3001 columns]

In [6]:
data[data.isnull().any(axis=1)]

Empty DataFrame
Columns: [Email No., the, to, ect, and, for, of, a, you, hou, in, on, is, this, enron, i, be, that, will, have, with, your, at, we, s, are, it, by, com, as, from, gas, or, not, me, deal, if, meter, hpl, please, re, e, any, our, corp, can, d, all, has, was, know, need, an, forwarded, new, t, may, up, j, mmbtu, should, do, am, get, out, see, no, there, price, daren, but, been, company, l, these, let, so, would, m, into, xls, farmer, attached, us, information, they, message, day, time, my, one, what, only, http, th, volume, mail, contract, which, month, ...]
Index: []

[0 rows x 3002 columns]

In [10]:
data.drop(['Email No.'],axis=1,inplace=True)
data.columns

Index(['the', 'to', 'ect', 'and', 'for', 'of', 'a', 'you', 'hou', 'in',
       ...
       'connevey', 'jay', 'valued', 'lay', 'infrastructure', 'military',
       'allowing', 'ff', 'dry', 'Prediction'],
      dtype='object', length=3001)

In [11]:
X = data.drop(['Prediction'],axis=1)
y = data['Prediction']

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=41)

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [14]:
from sklearn.svm import SVC
svr_lin = SVC(kernel='linear',C=100,gamma='auto')
svr_lin.fit(X_train,y_train)
y_pred_lin = svr_lin.predict(X_test)

In [16]:
svr_rbf = SVC(kernel='rbf',C=100,gamma=0.1)
svr_rbf.fit(X_train,y_train)
y_pred_rbf = svr_rbf.predict(X_test)

In [17]:
svr_poly = SVC(kernel='poly',C=100,gamma='auto',degree=3,coef0=1)
svr_poly.fit(X_train,y_train)
y_pred_poly = svr_poly.predict(X_test)

In [18]:
svr_sig = SVC(kernel='sigmoid',C=100,gamma='auto',coef0=1)
svr_sig.fit(X_train,y_train)
y_pred_sig = svr_sig.predict(X_test)

In [20]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,average_precision_score
cm = confusion_matrix(y_test,y_pred_lin)
print(cm)

[[1053   40]
 [  52  407]]


In [21]:
cr = classification_report(y_test,y_pred_lin)
print(cr)

              precision    recall  f1-score   support

           0       0.95      0.96      0.96      1093
           1       0.91      0.89      0.90       459

    accuracy                           0.94      1552
   macro avg       0.93      0.93      0.93      1552
weighted avg       0.94      0.94      0.94      1552



In [22]:
accuracy_score(y_test,y_pred_lin)

0.9407216494845361

In [23]:
average_precision_score(y_test,y_pred_lin)

0.8408677218385631

In [24]:
cm = confusion_matrix(y_test,y_pred_rbf)
print(cm)

[[1093    0]
 [ 423   36]]


In [26]:
cr = classification_report(y_test,y_pred_rbf)
print(cr)

              precision    recall  f1-score   support

           0       0.72      1.00      0.84      1093
           1       1.00      0.08      0.15       459

    accuracy                           0.73      1552
   macro avg       0.86      0.54      0.49      1552
weighted avg       0.80      0.73      0.63      1552



In [27]:
accuracy_score(y_test,y_pred_rbf)


0.7274484536082474

In [28]:
average_precision_score(y_test,y_pred_rbf)

0.3509829189407722

In [29]:
cm = confusion_matrix(y_test,y_pred_poly)
print(cm)

[[1055   38]
 [  53  406]]


In [30]:
cr = classification_report(y_test,y_pred_poly)
print(cr)

              precision    recall  f1-score   support

           0       0.95      0.97      0.96      1093
           1       0.91      0.88      0.90       459

    accuracy                           0.94      1552
   macro avg       0.93      0.92      0.93      1552
weighted avg       0.94      0.94      0.94      1552



In [35]:
accuracy_score(y_test,y_pred_poly)


0.9413659793814433

In [36]:
average_precision_score(y_test,y_pred_poly)

0.8429779208154992

In [32]:
cm = confusion_matrix(y_test,y_pred_sig)
print(cm)

[[959 134]
 [151 308]]


In [33]:
cr = classification_report(y_test,y_pred_sig)
print(cr)

              precision    recall  f1-score   support

           0       0.86      0.88      0.87      1093
           1       0.70      0.67      0.68       459

    accuracy                           0.82      1552
   macro avg       0.78      0.77      0.78      1552
weighted avg       0.81      0.82      0.82      1552



In [37]:
accuracy_score(y_test,y_pred_sig)


0.8163659793814433

In [38]:
average_precision_score(y_test,y_pred_sig)

0.564885174757914