NUMPY

1.How to extract all odd numbers from arr?




In [ ]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
odd_numbers = arr[arr%2 != 0]

print(odd_numbers)

[1 3 5 7 9]


2.Replace all odd numbers in arr with -1 without changing



In [ ]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
a = arr%2 != 0
arr[a] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


3. Convert a 1D array to a 2D array with 2 rows




In [ ]:
import numpy as np

arr=np.arange(10)
array_2d = arr.reshape(2,-1)
print(array_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


4.Stack arrays a and b vertically



In [ ]:
import numpy as np

a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)

result = np.vstack((a,b))

print(result)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


5.Stack the arrays a and b horizontally.

In [ ]:
import numpy as np
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
result = np.hstack((a,b))
print(result)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


6.How to get the common items between two python numpy arrays?
Get the common items between a and b

In [ ]:
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
result = np.intersect1d(a,b)
print(result)

[2 4]


7.How to remove from one array those items that exist in another?

Q. From array a remove all items present in array b

In [ ]:
import numpy as np

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
result = np.setdiff1d(a,b)
print(result)

[1 2 3 4]


8. How to get the positions where elements of two arrays match?

Q. Get the positions where elements of a and b match

In [ ]:
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
result = np.where(a==b)
print(result)

(array([1, 3, 5, 7]),)


9. How to extract all numbers between a given range from a numpy array?

Get all items between 5 and 10 from a

In [ ]:
import numpy as np

a = np.array([2, 6, 1, 9, 10, 3, 27])
result = a[(a >= 5) & (a <= 10)]
print(result)

[ 6  9 10]


PANDAS

PANDAS DATASERIES

##1. Write a Pandas program to convert a dictionary to a Pandas series.


In [ ]:
import pandas as pd
Original_dictionary = {'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
converted = pd.Series(Original_dictionary)
print("Converted Series")
print(converted)

Converted Series
a    100
b    200
c    300
d    400
e    800
dtype: int64


2. Write a Pandas program to convert a NumPy array to a Pandas series.

In [ ]:
import pandas as pd
import numpy as np
numpy_array = np.array([10,20,30,40,50])
converted = pd.Series(numpy_array)
print("Converted pandas series")
print(converted)

Converted pandas series
0    10
1    20
2    30
3    40
4    50
dtype: int64


3. Write a Pandas program to change the data type of given a column or a Series.

In [ ]:
import pandas as pd
original_series = pd.Series(['100', '200', 'python', '300.12', '400'])
converted = pd.to_numeric(original_series, errors='coerce')
print("Changed the said datatype to numeric:")
print(converted)

Changed the said datatype to numeric:
0    100.00
1    200.00
2       NaN
3    300.12
4    400.00
dtype: float64


5. Write a Pandas program to convert a given Series to an array.

In [ ]:
import pandas as pd
original_series = pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Series")
print(original_series)
array_series = original_series.to_numpy()
print("Series of array")
print(array_series)
print(type(array_series))

Original Series
0       100
1       200
2    python
3    300.12
4       400
dtype: object
Series of array
['100' '200' 'python' '300.12' '400']
<class 'numpy.ndarray'>


6 Write a Pandas program to convert Series of lists to one Series.

In [ ]:
import pandas as pd
original_series = pd.Series([['Red', 'Green', 'White'], ['Red', 'Black'], ['Yellow']])
print("Original Series")
print(original_series)
one_series = original_series.explode()
one_series = one_series.reset_index(drop = True)
print("One Series")
print(one_series)

Original Series
0    [Red, Green, White]
1           [Red, Black]
2               [Yellow]
dtype: object
One Series
0       Red
1     Green
2     White
3       Red
4     Black
5    Yellow
dtype: object


7.Write a Pandas program to sort a given Series.

In [ ]:
import pandas as pd
original_series = pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Series")
print(original_series)
sorted_series = original_series.sort_values()
print("Sorted Values")
print(sorted_series)

Original Series
0       100
1       200
2    python
3    300.12
4       400
dtype: object
Sorted Values
0       100
1       200
3    300.12
4       400
2    python
dtype: object


Pandas DataFrame

1.Write a Pandas program to create a dataframe from a dictionary and display it.

In [ ]:
import pandas as pd
Sample_data = {'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]}
df = pd.DataFrame(Sample_data)
print("Expected Output")
print(df)

Expected Output
    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83


2. Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the index labels.

In [ ]:
import pandas as pd
import numpy as np
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
    }
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index = labels)
print("Expected Output")
print(df)

Expected Output
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes


3. Write a Pandas program to get the first 3 rows of a given DataFrame.

In [ ]:
import pandas as pd
import numpy as np
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
    }
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index = labels)
print("Expected Output")
print(df.head(3))

Expected Output
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes


4.Write a Pandas program to select the 'name' and 'score' columns from the following DataFrame.

In [ ]:
import pandas as pd
import numpy as np
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
    }
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index = labels)
selected_columns = df[['name','score']]
print("Expected Output")
print(selected_columns)

Expected Output
        name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0


5. Write a Pandas program to select the specified columns and rows from a given data frame.

In [ ]:
import pandas as pd
import numpy as np
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
    }
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index = labels)
selected_data = df.loc[['b','d','f','g'],['score','qualify']]
print("Expected Output")
print(selected_data)

Expected Output
   score qualify
b    9.0      no
d    NaN      no
f   20.0     yes
g   14.5     yes


6. Write a Pandas program to select the rows where the number of attempts in the examination is greater than 2.

In [ ]:
import pandas as pd
import numpy as np
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
    }
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index = labels)
selected_rows = df[df['attempts']>2]
print("Expected Output")
print(selected_rows)

Expected Output
      name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes


7. Write a Pandas program to select the rows where the score is missing, i.e. is NaN.

In [ ]:
import pandas as pd
import numpy as np
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
    }
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index = labels)
missing_score = df[df['score'].isna()]
print("Expected Output")
print(missing_score)

Expected Output
    name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no


8. Write a Pandas program to select the rows the score is between 15 and 20 (inclusive).

In [ ]:
import pandas as pd
import numpy as np
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
    }
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index = labels)
selected_score = df[(df['score']>=15) & (df['score']<=20)]
print("Expected Output")
print(selected_score)

Expected Output
        name  score  attempts qualify
c  Katherine   16.5         2     yes
f    Michael   20.0         3     yes
j      Jonas   19.0         1     yes


9. Write a Pandas program to select the rows where number of attempts in the examination is less than 2 and score greater than 15.

In [ ]:
import pandas as pd
import numpy as np
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
    }
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index = labels)
selected_rows = df[(df['attempts']<2) & (df['score']>15)]
print("Expected Output")
print(selected_rows)

Expected Output
    name  score  attempts qualify
j  Jonas   19.0         1     yes


10. Write a Pandas program to change the score in row 'd' to 11.5.

In [ ]:
import pandas as pd
import numpy as np
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
    }
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index = labels)
df.loc['d','score'] = 11.5
print("Expected Output")
print(df)

Expected Output
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes


11. Write a Pandas program to calculate the sum of the examination attempts by the students.

In [ ]:
import pandas as pd
import numpy as np
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
    }
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index = labels)
sum_attempts = df['attempts'].sum()
print("Sum of  the examination attempts by the students")
print(sum_attempts)

Sum of  the examination attempts by the students
19


12. Write a Pandas program to calculate the mean of all students' scores. Data is stored in a dataframe.

In [ ]:
import pandas as pd
import numpy as np
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
    }
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index = labels)
mean_score = df['score'].mean()
print("Mean score for each different student in data frame")
print(mean_score)

Mean score for each different student in data frame
13.5625


13. Write a Pandas program to replace the 'qualify' column contains the values 'yes' and 'no' with True and False.

In [ ]:
import pandas as pd
import numpy as np
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
    }
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index = labels)
df['qualify'] = df['qualify'].replace({'yes':True, 'no':False})
print("Replace the 'qualify' column contains the values 'yes' and 'no' with true and false")
print(df)

Replace the 'qualify' column contains the values 'yes' and 'no' with true and false
        name  score  attempts  qualify
a  Anastasia   12.5         1     True
b       Dima    9.0         3    False
c  Katherine   16.5         2     True
d      James    NaN         3    False
e      Emily    9.0         2    False
f    Michael   20.0         3     True
g    Matthew   14.5         1     True
h      Laura    NaN         1    False
i      Kevin    8.0         2    False
j      Jonas   19.0         1     True


14. Write a Pandas program to change the name 'James' to 'Suresh' in name column of the DataFrame.

In [ ]:
import pandas as pd
import numpy as np
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
    }
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index = labels)
df['name'] = df['name'].replace('James', 'Suresh')
print("Change the name James to Suresh")
print(df)

Change the name James to Suresh
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d     Suresh    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes


15. Write a Pandas program to delete the 'attempts' column from the DataFrame.

In [ ]:
import pandas as pd
import numpy as np
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
    }
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index = labels)
df = df.drop('attempts',axis = 1)
print("Delete the 'attempts' column from the data frame: ")
print(df)

Delete the 'attempts' column from the data frame: 
        name  score qualify
a  Anastasia   12.5     yes
b       Dima    9.0      no
c  Katherine   16.5     yes
d      James    NaN      no
e      Emily    9.0      no
f    Michael   20.0     yes
g    Matthew   14.5     yes
h      Laura    NaN      no
i      Kevin    8.0      no
j      Jonas   19.0     yes


16. Write a Pandas program to insert a new column in existing DataFrame.

In [ ]:
import pandas as pd
import numpy as np
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
    }
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index = labels)
df = df.assign(color = ['Red','Blue','Red','Blue','Blue','Red','Red','Blue','Green','Red'])
print("New DataFrame after inserting the 'color' column ")
print(df)

New DataFrame after inserting the 'color' column 
        name  score  attempts qualify  color
a  Anastasia   12.5         1     yes    Red
b       Dima    9.0         3      no   Blue
c  Katherine   16.5         2     yes    Red
d      James    NaN         3      no   Blue
e      Emily    9.0         2      no   Blue
f    Michael   20.0         3     yes    Red
g    Matthew   14.5         1     yes    Red
h      Laura    NaN         1      no   Blue
i      Kevin    8.0         2      no  Green
j      Jonas   19.0         1     yes    Red


17. Write a Pandas program to rename columns of a given DataFrame

In [ ]:
import pandas as pd
sample_date = {'col1': [1, 2, 3], 'col2': [4, 5, 6], 'col3': [7, 8, 9]}
df = pd.DataFrame(sample_date)
print("Original Dataframe")
print(df)
df = df.rename(columns = {'col1':'Column1', 'col2':'Column2', 'col3':'Column3'})
print("New DataFrame after renaming columns:")
print(df)

Original Dataframe
   col1  col2  col3
0     1     4     7
1     2     5     8
2     3     6     9
New DataFrame after renaming columns:
   Column1  Column2  Column3
0        1        4        7
1        2        5        8
2        3        6        9


18. Write a Pandas program to select rows from a given DataFrame based on values in some columns.

In [ ]:
import pandas as pd
data = {'col1': [1, 4, 3, 4, 5],
        'col2': [4, 5, 6, 7, 8],
        'col3': [7, 8, 9, 0, 1]}
df = pd.DataFrame(data)
print("Original DataFrame")
print(df)
selected_rows = df[df['col1']==4]
print("Rows for colum1 value == 4")
print(selected_rows)

Original DataFrame
   col1  col2  col3
0     1     4     7
1     4     5     8
2     3     6     9
3     4     7     0
4     5     8     1
Rows for colum1 value == 4
   col1  col2  col3
1     4     5     8
3     4     7     0


19. Write a Pandas program to add one row in an existing DataFrame.

In [ ]:
import pandas as pd
data = {'col1': [1, 4, 3, 4, 5],
        'col2': [4, 5, 6, 7, 8],
        'col3': [7, 8, 9, 0, 1]}
df = pd.DataFrame(data)
print("Original DataFrame")
print(df)
new_row = {'col1':10, 'col2':11, 'col3':12}
df = df.append(new_row, ignore_index=True)
print("After add one row:")
print(df)

Original DataFrame
   col1  col2  col3
0     1     4     7
1     4     5     8
2     3     6     9
3     4     7     0
4     5     8     1
After add one row:
   col1  col2  col3
0     1     4     7
1     4     5     8
2     3     6     9
3     4     7     0
4     5     8     1
5    10    11    12


<ipython-input-11-ddddaa5a9459>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)


20. Write a Pandas program to replace all the NaN values with Zero's in a column of a dataframe.

In [ ]:
import pandas as pd
import numpy as np
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
    }
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index = labels)
print("Original DataFrame")
print(df)
df = df.fillna(0)
print("New DataFrame replacing all NaN with 0:")
print(df)

Original DataFrame
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes
New DataFrame replacing all NaN with 0:
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    0.0         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    0.0         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes


21. Write a Pandas program to count the NaN values in one or more columns in DataFrame.

In [ ]:
import pandas as pd
import numpy as np
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
    }
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index = labels)
print("Original DataFrame")
print(df)
df = df.isna().sum().sum()
print("Number of NaN values in one or more columns:")
print(df)

Original DataFrame
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes
Number of NaN values in one or more columns:
2


22. Write a Pandas program to drop a list of rows from a specified DataFrame.

In [ ]:
import pandas as pd
data = {'col1': [1, 4, 3, 4, 5],
        'col2': [4, 5, 6, 7, 8],
        'col3': [7, 8, 9, 0, 1]}

df = pd.DataFrame(data)
print("Original DataFrame")
print(df)
df = df.drop(df.index[[2,4]])
print("New DataFrame after removing 2nd & 4th rows:")
print(df)

Original DataFrame
   col1  col2  col3
0     1     4     7
1     4     5     8
2     3     6     9
3     4     7     0
4     5     8     1
New DataFrame after removing 2nd & 4th rows:
   col1  col2  col3
0     1     4     7
1     4     5     8
3     4     7     0


23. . Write a Pandas program to convert DataFrame column type from string to datetime.

In [ ]:
import pandas as pd
string_dates = pd.Series(['3/11/2000', '3/12/2000', '3/13/2000'])
print("String Dates")
print(string_dates)
date_time_column = pd.to_datetime(string_dates)
df = pd.DataFrame({0: date_time_column})
print("Original DataFrame (string to datetime):")
print(df)

String Dates
0    3/11/2000
1    3/12/2000
2    3/13/2000
dtype: object
Original DataFrame (string to datetime):
           0
0 2000-03-11
1 2000-03-12
2 2000-03-13


24. Write a Pandas program to find the row for where the value of a given column is maximum.

In [ ]:
import pandas as pd
data = {'col1': [1, 2, 3, 4, 7],
        'col2': [4, 5, 6, 9, 5],
        'col3': [7, 8, 12, 1, 11]}

df = pd.DataFrame(data)
print("Original DataFrame")
print(df)
max_col1_row = df['col1'].argmax()
max_col2_row = df['col2'].argmax()
max_col3_row = df['col3'].argmax()
print("Row where col1 has maximum value:")
print(max_col1_row)
print("Row where col2 has maximum value:")
print(max_col2_row)
print("Row where col3 has maximum value:")
print(max_col3_row)

Original DataFrame
   col1  col2  col3
0     1     4     7
1     2     5     8
2     3     6    12
3     4     9     1
4     7     5    11
Row where col1 has maximum value:
4
Row where col2 has maximum value:
3
Row where col3 has maximum value:
2


25. Write a Pandas program to get the datatypes of columns of a DataFrame.

In [ ]:
import pandas as pd
import numpy as np
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
    }
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index = labels)
print("Original DataFrame")
print(df)
column_datatypes = df.dtypes
print("Data types of the columns of the said DataFrame:")
print(column_datatypes)

Original DataFrame
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes
Data types of the columns of the said DataFrame:
name         object
score       float64
attempts      int64
qualify      object
dtype: object


26. Write a Pandas program to group by the first column and get second column as lists in rows.

In [ ]:
import pandas as pd
data = {'col1': ['C1', 'C1', 'C2', 'C2', 'C2', 'C3', 'C2'],
        'col2': [1, 2, 3, 3, 4, 6, 5]}
df = pd.DataFrame(data)
result = df.groupby('col1')['col2'].agg(list)
print("Group on the col1:")
print(result)

Group on the col1:
col1
C1          [1, 2]
C2    [3, 3, 4, 5]
C3             [6]
Name: col2, dtype: object


27 Write a Pandas program to count number of columns of a DataFrame.

In [ ]:
import pandas as pd

data = {'col1': [1, 2, 3, 4, 7],
        'col2': [4, 5, 6, 9, 5],
        'col3': [7, 8, 12, 1, 11]}

df = pd.DataFrame(data)
print("Original DataFrame")
print(df)
num_columns = df.shape[1]
print("Number of columns:")
print(num_columns)

Original DataFrame
   col1  col2  col3
0     1     4     7
1     2     5     8
2     3     6    12
3     4     9     1
4     7     5    11
Number of columns:
3


28. Write a Pandas program to get first n records of a DataFrame.

In [ ]:
import pandas as pd

data = {'col1': [1, 2, 3, 4, 7, 11],
        'col2': [4, 5, 6, 9, 5, 0],
        'col3': [7, 5, 8, 12, 1, 11]}

df = pd.DataFrame(data)
print("Original DataFrame")
print(df)
records = df.head(3)
print("First 3 rows of the said DataFrame:")
print(records)

Original DataFrame
   col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     0    11
First 3 rows of the said DataFrame:
   col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8


29. Write a Pandas program to get last n records of a DataFrame.

In [ ]:
import pandas as pd

data = {'col1': [1, 2, 3, 4, 7, 11],
        'col2': [4, 5, 6, 9, 5, 0],
        'col3': [7, 5, 8, 12, 1, 11]}

df = pd.DataFrame(data)
print("Original DataFrame")
print(df)
records = df.tail(3)
print("Last 3 rows of the said DataFrame:")
print(records)

Original DataFrame
   col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     0    11
Last 3 rows of the said DataFrame:
   col1  col2  col3
3     4     9    12
4     7     5     1
5    11     0    11


30. Write a Pandas program to get topmost n records within each group of a DataFrame.

In [ ]:
import pandas as pd

data = {'col1': [1, 2, 3, 4, 7, 11],
        'col2': [4, 5, 6, 9, 5, 0],
        'col3': [7, 5, 8, 12, 1, 11]}

df = pd.DataFrame(data)
print("Original DataFrame")
print(df)
df1 = df.nlargest(3,'col1')
df2 = df.nlargest(4,'col2')
df3 = df.nlargest(3,'col3')
print("topmost n records within each group of a DataFrame:")
print(df1)
print(df2)
print(df3)

Original DataFrame
   col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     0    11
topmost n records within each group of a DataFrame:
   col1  col2  col3
5    11     0    11
4     7     5     1
3     4     9    12
   col1  col2  col3
3     4     9    12
2     3     6     8
1     2     5     5
4     7     5     1
   col1  col2  col3
3     4     9    12
5    11     0    11
2     3     6     8


31. Write a Pandas program to add a prefix or suffix to all columns of a given DataFrame.

In [ ]:
import pandas as pd

data = {'W': [68, 75, 86, 80, 66],
        'X': [78, 85, 96, 80, 86],
        'Y': [84, 94, 89, 83, 86],
        'Z': [86, 97, 96, 72, 83]}

df = pd.DataFrame(data)
print("original DataFrame")
print(df)
add_prefix = df.add_prefix('A_')
add_suffix = df.add_suffix('_1')
print("Add prefix:")
print(add_prefix)
print("Add suffix:")
print(add_suffix)

original DataFrame
    W   X   Y   Z
0  68  78  84  86
1  75  85  94  97
2  86  96  89  96
3  80  80  83  72
4  66  86  86  83
Add prefix:
   A_W  A_X  A_Y  A_Z
0   68   78   84   86
1   75   85   94   97
2   86   96   89   96
3   80   80   83   72
4   66   86   86   83
Add suffix:
   W_1  X_1  Y_1  Z_1
0   68   78   84   86
1   75   85   94   97
2   86   96   89   96
3   80   80   83   72
4   66   86   86   83


32. Write a Pandas program to convert continuous values of a column in a given DataFrame to categorical.

In [ ]:
import pandas as pd
df = pd.DataFrame({
    'name': ['Alberto Franco','Gino Mcneill','Ryan Parkes', 'Eesha Hinton', 'Syed Wharton', 'Kierra Gentry'],
      'age': [18, 22, 85, 50, 80, 5]
})
print("Original DataFrame")
print(df)
print("Age Group")
df['age_group'] = pd.cut(df['age'],bins = [0,18,22,99],labels = ["kids","adult",'elderly'])
print(df['age_group'])

Original DataFrame
             name  age
0  Alberto Franco   18
1    Gino Mcneill   22
2     Ryan Parkes   85
3    Eesha Hinton   50
4    Syed Wharton   80
5   Kierra Gentry    5
Age Group
0       kids
1      adult
2    elderly
3    elderly
4    elderly
5       kids
Name: age_group, dtype: category
Categories (3, object): ['kids' < 'adult' < 'elderly']


33. Write a Pandas program to append rows to an existing DataFrame and display the combined data.

In [ ]:
import pandas as pd

student_data1 = pd.DataFrame({
    'student_id': ['S1', 'S2', 'S3', 'S4', 'S5'],
    'name': ['Danniella Fenton', 'Ryder Storey', 'Bryce Jensen', 'Ed Bernal', 'Kwame Morin'],
    'marks': [200, 210, 190, 222, 199]
})
print("Original DataFrame")
print(student_data1)
new_row = pd.Series({'studend_id':'S6','name':'Scarlette Fisher','marks':205})
print("New Row")
print(new_row)
combined_row = student_data1.append(new_row, ignore_index=True)
print("Combined Row")
print(combined_row)

Original DataFrame
  student_id              name  marks
0         S1  Danniella Fenton    200
1         S2      Ryder Storey    210
2         S3      Bryce Jensen    190
3         S4         Ed Bernal    222
4         S5       Kwame Morin    199
New Row
studend_id                  S6
name          Scarlette Fisher
marks                      205
dtype: object
Combined Row
  student_id              name  marks studend_id
0         S1  Danniella Fenton    200        NaN
1         S2      Ryder Storey    210        NaN
2         S3      Bryce Jensen    190        NaN
3         S4         Ed Bernal    222        NaN
4         S5       Kwame Morin    199        NaN
5        NaN  Scarlette Fisher    205         S6


<ipython-input-16-e62a1b74e3e7>:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  combined_row = student_data1.append(new_row, ignore_index=True)


34 Write a Pandas program to join the two given dataframes along rows and merge with another dataframe along the common column id.


In [ ]:
import pandas as pd
student_data1 = pd.DataFrame({
        'student_id': ['S1', 'S2', 'S3', 'S4', 'S5'],
         'name': ['Danniella Fenton', 'Ryder Storey', 'Bryce Jensen', 'Ed Bernal', 'Kwame Morin'],
        'marks': [200, 210, 190, 222, 199]})

student_data2 = pd.DataFrame({
        'student_id': ['S4', 'S5', 'S6', 'S7', 'S8'],
        'name': ['Scarlette Fisher', 'Carla Williamson', 'Dante Morse', 'Kaiser William', 'Madeeha Preston'],
        'marks': [201, 200, 198, 219, 201]})

exam_data = pd.DataFrame({
        'student_id': ['S1', 'S2', 'S3', 'S4', 'S5', 'S7', 'S8', 'S9', 'S10', 'S11', 'S12', 'S13'],
        'exam_id': [23, 45, 12, 67, 21, 55, 33, 14, 56, 83, 88, 12]})

print("Original DataFrames:")
print(student_data1)
print(student_data2)
print(exam_data)

print("\nJoin first two said dataframes along rows:")
result_data = pd.concat([student_data1, student_data2])
print(result_data)

print("\nNow join the said result_data and df_exam_data along student_id:")
final_merged_data = pd.merge(result_data, exam_data, on='student_id')
print(final_merged_data)


Original DataFrames:
  student_id              name  marks
0         S1  Danniella Fenton    200
1         S2      Ryder Storey    210
2         S3      Bryce Jensen    190
3         S4         Ed Bernal    222
4         S5       Kwame Morin    199
  student_id              name  marks
0         S4  Scarlette Fisher    201
1         S5  Carla Williamson    200
2         S6       Dante Morse    198
3         S7    Kaiser William    219
4         S8   Madeeha Preston    201
   student_id  exam_id
0          S1       23
1          S2       45
2          S3       12
3          S4       67
4          S5       21
5          S7       55
6          S8       33
7          S9       14
8         S10       56
9         S11       83
10        S12       88
11        S13       12

Join first two said dataframes along rows:
  student_id              name  marks
0         S1  Danniella Fenton    200
1         S2      Ryder Storey    210
2         S3      Bryce Jensen    190
3         S4         Ed Bern